POST http://localhost:3003/api/users
Content-type: application/json

{
    "username": "spurtilo",
    "name": "Simo Purtilo",
    "password": "salainensana"
}

# {
#     "username": "teppo",
#     "name": "Teppo Testinen",
#     "password": "dsadgdfgfd"
# }
