POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcHBvIiwiaWQiOiI2NWRmMDMzOWYxNGZjNGIxOTNhN2U0NWEiLCJpYXQiOjE3MDkxMjg2Mjl9.fxmsyLhaMCn_y6utY_u-WBqbfRgH9IVMI06dFlLM6TA

{
  "author": "Teppogdfg Testimies",
  "url": "http://www.example.com/Blog3",
  "title": "blog4 name",
  "likes": 1
}