POST http://localhost:3003/api/users
Content-type: application/json

# {
#     "username": "simo@fakemail.com",
#     "name": "Simo Purtilo",
#     "password": "secret"
# }

{
    "username": "seppo@jokumaili.fi",
    "name": "Seppo Sepponen",
    "password": "secret"
}
