POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbW9AZmFrZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTczODE3NTM3N30.LDXOwWNPNj19NhEnDlLaevxt7Fw4TAdHfaiKe5gaIpg

{
  "author": "Seppo Testimies",
  "url": "http://www.example.com/Blog5",
  "title": "blog5 name",
  "year": "1996"
}