DELETE http://localhost:3003/api/blogs/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcHBvIiwiaWQiOiI2NWRmMDMzOWYxNGZjNGIxOTNhN2U0NWEiLCJpYXQiOjE3MDkxMjg2Mjl9.fxmsyLhaMCn_y6utY_u-WBqbfRgH9IVMI06dFlLM6TA

# simon token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNwdXJ0aWxvIiwiaWQiOiI2NWRmMDMyZmYxNGZjNGIxOTNhN2U0NTgiLCJpYXQiOjE3MDkxMzE4NjV9.WmCa_yBYneJnuH1vKBOL8kk9GAb9ioC01CAirp0d-AY

# tepon token: 

